### ISSUE TITLE
Krypton nightly -- script.videoextras: BaseExtrasItem: Traceback

### ISSUE THREAD

**Issue by thezoggy** [robwebset/script.videoextras#5]
running latest Krypton nightly (kodi-20161229-61cd863-Krypton-armeabi-v7a.apk), noticed videoextras throwing traceback:
```
21:28:34.433 T:18446744072291504056   ERROR: script.videoextras: BaseExtrasItem: Traceback (most recent call last):

                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.videoextras/resources/lib/ExtrasItem.py", line 300, in _loadNfoInfo

                                                nfoXml = ET.ElementTree(ET.fromstring(nfoFileStr.decode("UTF-8", 'ignore')))

                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML

                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed

                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror

                                            ParseError: syntax error: line 1, column 0
```

**Comment by thezoggy** [comment]
scene nfo, not properly formatted to what videoextras wants.. sorry about that
